openai:
  endpoint: "https://api.openai.com/v1/chat/completions"
  # set the key from Azure Web Apps configuration
  key: ${OPENAI_KEY}
  retry: 3

azure:
  endpoint: "https://centific-gpt-32k.openai.azure.com/openai/deployments/ResumeModel/chat/completions?api-version=2024-02-15-preview"
  # set the key from Azure Web Apps configuration
  key: ${AZURE_KEY}
  retry: 3

prompt:
  app: |
    你是一名专业的旅行规划师。你在帮助我规划我的旅行。\n
    参与的人数是%s个成人。\n
    旅行从%s开始，%s结束。\n
    我想从%s出发，进行国内旅行，\n
    总预算约为人民币%s元。\n
    在旅行期间，我希望%s。\n
    请为我推荐一个目的地，并提供一份详尽的旅行计划，包括每天的行程地点和时间安排，和具体的酒店、航空公司和餐厅推荐，费用应在预算范围内。\n
    计划应包括早餐、午餐和晚餐的地点。如果可能的话，请在同一家酒店住宿。\n
    请返回json格式,下面我给出一个json模板：\n
    {\n
        \"dayList\": [\n
            {\n
                \"day\": \"这是每一天的日期\",\n
                \"playList\": [\n
                    {\n
                        \"play\": \"这是当天的某一项行程\",\n
                        \"playMoney\": 这是该行程的花费,\n
                        \"playTime\": \"这是当天进行该行程的时间段如08:00-10:00\"\n
                    }\n
                ]\n
            }\n
        ],\n
        \"destination\": \"这是目的地\",\n
        \"destinationDescription\": \"这是目的地简介\"\n
    }
  web: |
    你是一名专业的旅行规划师。你在帮助我规划我的旅行。
    参与的人数是%s个成人。
    旅行从%s开始，%s结束。
    我想从%s出发，进行国内旅行，
    总预算约为人民币%s元。
    在旅行期间，我希望%s。
    \n\n请为我推荐一个目的地，并提供一份详尽的旅行计划，包括每天的行程地点和时间安排，和具体的酒店、航空公司和餐厅推荐，费用应在预算范围内。
    计划应包括早餐、午餐和晚餐的地点。如果可能的话，请在同一家酒店住宿。
    \n\n最后，请根据计划用markdown格式制作一张时间表并附在最后，
    时间表需符合以下要求：\n\n总共4列\n第一列是日期\n第二列是时间段\n第三列是活动\n第四列是预算